### ISSUE TITLE
Warble 1.3.0 does not work with rake 0.9.0 

### ISSUE THREAD

**Issue by patcheng** [jruby/warbler#30]
warble aborted!
undefined method `task' for #Warbler::Config:0x6469cee6
