### ISSUE TITLE
Error with flash notifications in compiled war file

### ISSUE THREAD

**Issue by amelief** [jruby/warbler#418]
Currently experiencing an issue with a compiled war file. The war builds and deploys fine but whenever a flash notification is encountered I receive the following error:

> Java::JavaLang::NoSuchMethodError (rubyobj.ActionDispatch.Flash.FlashHash.callMethod(Ljava/lang/String;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;):
> rubyobj.ActionDispatch.Flash.FlashHash.initialize_copy(Unknown Source)|  org.jruby.RubyKernel.initialize_copy(RubyKernel.java:1834)
> org.jruby.RubyKernel$INVOKER$s$1$0$initialize_copy.call(RubyKernel$INVOKER$s$1$0$initialize_copy.gen)| 
> org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:738)|  
> org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1006)|  
> org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)|  
> org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)|  
> org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)|  

Environment: Warbler 2.0.4, Rails 4.2.9, JRuby 9.1.5.0, OpenJDK 8 (1.8.0_131), rvm 1.29.1 on Ubuntu 16.04.

This is a basic rails app with no other gems than the defaults - can't seem to get past this issue. The application runs fine if I run it from the war file, i.e. `java -jar app.war -S rails s`  but not if I try to use the built-in jetty-runner or even an external jetty-runner.

Things I've tried:

- Changing the version of JRuby and jruby-jars - no change, though the error then also includes a stackoverflow exception as well as the above on 9.1.12.0, and causes a compilation error on 9.0.x - though it does appear to work on 9.0.0.0
- Updating jetty-runner to the latest - tried built-in 9.2.x and also 9.3.x and 9.4.x
- Downgrading warbler to 2.0.0
- Using the default warble.rb, and/or changing build options within this. The only customised parts of warble.rb left are that config.features was changed to `%w(compiled runnable)`.

Originally this was happening in a rather large legacy Rails 3.2.22.5 application but a basic one-controller scaffold app in Rails 4.2.9 also appears to have this issue, which leads me to believe it is not an issue with the application but with the compilation process. Unfortunately I'm not in a position to try Rails 5 so I'm not sure if this works as expected.

Any ideas?
